import fs from "node:fs/promises";
import path from "node:path";
import {Presentation,PresentationFile} from "@oai/artifact-tool";
import {args,need,readJson,writeJson} from "./lib/common.mjs";
import {normalizedToPixels} from "./lib/composition-solver.mjs";

const a=args(),plan=await readJson(path.resolve(need(a,"plan"))),output=path.resolve(need(a,"output")),work=path.resolve(a.work||path.dirname(output));
if(!String(plan.plannerVersion||"").startsWith("5."))throw new Error("build-deck-v5 requires a Planner 5.0 plan");
const replans=plan.slides.filter(x=>x.composition_solution?.solver_status!=="feasible"||x.template_match?.match_status!=="matched");
if(replans.length)throw new Error(`NEEDS_CONTENT_REPLAN slides=${replans.map(x=>x.outputSlide).join(",")}`);
await fs.mkdir(path.dirname(output),{recursive:true});

const deck=Presentation.create({slideSize:{width:1280,height:720}}),C={canvas:"#F8F9FA",panel:"#EEF0F3",dark:"#202124",text:"#202124",muted:"#5F6368",line:"#DADCE0",white:"#FFFFFF",red:"#EA4335",orange:"#F57C35",yellow:"#FBBC04",green:"#34A853",teal:"#25A7A2",blue:"#4285F4",violet:"#5B3DF5"},fonts={latin:"Arial",cjk:"Microsoft YaHei"};
const linear=(colors,angle=0)=>`linear(${angle}deg, ${colors.map((color,index)=>`${color} ${Math.round(index/Math.max(colors.length-1,1)*100)}%`).join(", ")})`;
const p=value=>normalizedToPixels(value);
function shape(slide,geometry,position,fill="none",line="none",name){return slide.shapes.add({geometry,name,position,fill,line:{style:"solid",fill:line,width:line==="none"?0:1}});}
function text(slide,value,position,{fontSize=18,color=C.text,bold=false,alignment="left",name="text"}={}){const item=shape(slide,"textbox",position,"none","none",name);item.text=String(value??"");item.text.style={fontSize,color,bold,fontFamily:/[\u3400-\u9fff]/.test(String(value))?fonts.cjk:fonts.latin,alignment};return item;}
function fontFor(value,box,{hero=false,chapter=false}={}){const n=[...String(value||"")].reduce((sum,ch)=>sum+(/[\u3400-\u9fff]/.test(ch)?1.7:1),0),base=hero?78:chapter?72:46,fit=Math.sqrt(Math.max(box.width,180)/Math.max(n*12,160))*base;return Math.max(hero||chapter?46:35,Math.min(base,Math.floor(fit)));}
function bodyValue(content){return Array.isArray(content.body)?content.body.join("\n\n"):String(content.body||"");}
function itemValue(item){return typeof item==="object"?item.text||item.title||item.label||item.body||JSON.stringify(item):String(item);}
function paletteFor(slide){const value=String([slide.coreClaim,slide.narrative_role,slide.evidence_type].join(" ")).toLowerCase();if(/risk|security|investment|provider|风险|安全|投资/.test(value))return [C.green,C.teal,C.blue,C.violet];if(/growth|value|revenue|productivity|roi|增长|价值|收益/.test(value))return [C.yellow,"#8BC34A",C.green];return [C.red,C.orange,C.yellow];}
function addGradientMark(slide,position,colors){shape(slide,"rect",position,linear(colors,0),"none","gradient-data-mark");}
function addSource(slide,content,dark=false){const sources=(content.sources||[]).filter(Boolean);if(!sources.length)return;text(slide,sources.join(" · "),{left:48,top:681,width:1010,height:17},{fontSize:8,color:dark?"#B8BCC2":C.muted,name:"source-note"});}
function addFooter(slide,index,dark=false){text(slide,String(index).padStart(2,"0"),{left:1180,top:681,width:52,height:18},{fontSize:9,color:dark?"#B8BCC2":C.muted,alignment:"right",name:"page-number"});}
async function addSelectedAsset(slide,record){if(record.status!=="matched")return;const bytes=await fs.readFile(record.absolute_path),position=p(record.composition_target?.asset_visible_region||record.asset_visible_region||[.65,.45,.35,.55]);slide.images.add({blob:bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),contentType:"image/png",alt:`Original registered organic asset ${record.asset_id}`,fit:"cover",position,name:`organic-asset-${record.asset_id}`});}
async function addSourceImage(slide,content,position){const file=(content.images||[]).find(Boolean);if(!file)return false;try{const bytes=await fs.readFile(file),ext=path.extname(file).toLowerCase();slide.images.add({blob:bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),contentType:ext===".png"?"image/png":"image/jpeg",alt:"Source presentation image",fit:"cover",position,geometry:"roundRect",borderRadius:"rounded-xl"});return true;}catch{return false;}}
function addNativeChart(slide,content,position,dark=false){const data=(content.data||[]).filter(x=>Number.isFinite(Number(x.value))).slice(0,8);if(!data.length)return false;slide.charts.add("bar",{position,categories:data.map(x=>String(x.label||"")),series:[{name:content.chartTitle||"Value",values:data.map(x=>Number(x.value)||0),fill:dark?C.green:C.blue}],hasLegend:false,dataLabels:{showValue:true,position:"outEnd"},xAxis:{majorGridlines:{style:"solid",fill:dark?"#4A4D52":C.line,width:1}},yAxis:{majorGridlines:{style:"solid",fill:dark?"#4A4D52":C.line,width:1}}});return true;}
function addMetricSystem(slide,metrics,position,{dark=false,max=5}={}){const list=(metrics||[]).slice(0,max),count=Math.max(list.length,1),gap=18,width=(position.width-gap*(count-1))/count;list.forEach((metric,index)=>{const left=position.left+index*(width+gap);if(index)addGradientMark(slide,{left:left-9,top:position.top,width:1,height:position.height},[dark?"#59606E":C.line,dark?"#59606E":C.line]);text(slide,metric.value||metric.number||"—",{left,top:position.top+18,width,height:Math.min(108,position.height*.35)},{fontSize:Math.max(38,Math.min(62,Math.floor(width/4))),color:dark?C.white:C.text,bold:true,name:`metric-${index+1}`});text(slide,metric.label||metric.description||metric.sourceText||"",{left,top:position.top+128,width,height:Math.max(80,position.height-145)},{fontSize:14,color:dark?"#D5D8DD":C.muted,name:`metric-label-${index+1}`});});}
function addBroadField(slide,position,{dark=false,name="broad-field"}={}){return shape(slide,"roundRect",position,dark?"#303134":C.panel,"none",name);}

async function renderSlide(record){
  const slide=deck.slides.add(),content=record.content||{},solution=record.composition_solution,topology=record.evidence_topology?.kind||"reasoned_narrative",headlineBox=p(solution.headline_bbox),evidenceBox=p(solution.evidence_bbox),secondaryBox=p(solution.secondary_focal_bbox),clusterBox=p(solution.content_cluster_bbox),palette=paletteFor(record),dark=["T03","T23"].includes(record.templateId),split=["T13","T18"].includes(record.templateId);
  slide.background.fill=dark?C.dark:C.canvas;
  if(record.templateId==="T07")slide.background.fill=linear(palette,12);
  if(split){shape(slide,"rect",evidenceBox,C.dark,"none","dark-evidence-field");addGradientMark(slide,{left:evidenceBox.left,top:evidenceBox.top,width:Math.min(260,evidenceBox.width),height:10},palette);}
  if(record.templateId==="T23"){shape(slide,"ellipse",{left:850,top:300,width:430,height:420},`radial(${C.blue} 0%, ${C.blue}00 72%)`,"none","closing-spectrum-arc");shape(slide,"ellipse",{left:1010,top:500,width:270,height:220},`radial(${C.green} 0%, ${C.green}00 70%)`,"none","closing-spectrum-arc-secondary");}
  const assetSelection={...record.asset_selection,composition_target:record.asset_query?.composition_target};
  if(!dark&&!split)await addSelectedAsset(slide,assetSelection);
  const titleColor=record.templateId==="T07"||dark?C.white:C.text,titleSize=fontFor(content.title||record.coreClaim,headlineBox,{hero:record.semanticRole==="cover",chapter:record.page_type==="chapter"});

  if(topology==="single_thesis"){
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:titleColor,bold:true,name:"primary-headline"});
    const subtitle=content.subtitle||bodyValue(content);if(subtitle)text(slide,subtitle,{left:headlineBox.left+6,top:headlineBox.top+headlineBox.height+22,width:Math.min(600,headlineBox.width),height:96},{fontSize:20,color:C.muted,name:"subtitle"});
  }else if(topology==="narrative_transition"){
    text(slide,content.chapter||String(record.outputSlide).padStart(2,"0"),secondaryBox,{fontSize:28,color:C.white,bold:true,name:"section-number"});
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:C.white,bold:true,name:"primary-headline"});
  }else if(topology==="final_action"){
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:C.white,bold:true,name:"primary-headline"});
    text(slide,content.cta||content.contact||bodyValue(content),secondaryBox,{fontSize:20,color:C.white,bold:true,name:"call-to-action"});
  }else if(topology==="authority_testimony"){
    text(slide,"“",{left:Math.max(0,headlineBox.left-44),top:headlineBox.top-38,width:32,height:64},{fontSize:60,color:C.text,bold:true,name:"quote-mark"});
    text(slide,content.quote||content.quotes?.[0]?.text||record.coreClaim,headlineBox,{fontSize:Math.max(28,Math.min(40,titleSize)),color:C.text,name:"primary-quote"});
    text(slide,content.attribution||"",secondaryBox,{fontSize:14,color:C.muted,bold:true,alignment:"right",name:"attribution"});
  }else if(topology==="summary_plus_kpi"){
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:C.text,bold:true,name:"primary-headline"});
    text(slide,bodyValue(content),{left:clusterBox.left,top:headlineBox.top+headlineBox.height+18,width:Math.max(420,evidenceBox.left-clusterBox.left-50),height:330},{fontSize:16,color:C.text,name:"summary-body"});
    const metric=(content.metrics||[])[0]||{value:"—",label:"Key evidence"};addGradientMark(slide,{left:evidenceBox.left,top:evidenceBox.top,width:evidenceBox.width,height:10},palette);text(slide,metric.value||"—",{left:evidenceBox.left,top:evidenceBox.top+32,width:evidenceBox.width,height:110},{fontSize:62,color:C.text,bold:true,name:"hero-metric"});text(slide,metric.label||"",{left:evidenceBox.left,top:evidenceBox.top+154,width:evidenceBox.width,height:120},{fontSize:16,color:C.text,name:"metric-meaning"});
  }else if(topology==="decisive_kpi"){
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:C.text,bold:true,name:"primary-headline"});const metric=(content.metrics||[])[0]||{value:"—",label:""};text(slide,metric.value||"—",evidenceBox,{fontSize:Math.max(68,Math.min(104,evidenceBox.width/4)),color:C.text,bold:true,name:"hero-metric"});text(slide,metric.label||metric.description||"",secondaryBox,{fontSize:19,color:C.muted,name:"metric-meaning"});
  }else if(topology==="statistical_proof"||topology==="narrative_single_chart"){
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:C.text,bold:true,name:"primary-headline"});
    if(topology==="narrative_single_chart")text(slide,bodyValue(content),secondaryBox,{fontSize:16,color:C.text,name:"supporting-narrative"});
    if(!addNativeChart(slide,content,{left:evidenceBox.left+40,top:evidenceBox.top+95,width:Math.max(320,evidenceBox.width-80),height:Math.max(260,evidenceBox.height-150)},true))addMetricSystem(slide,content.metrics,evidenceBox,{dark:true});
  }else if(topology==="comparable_metrics"||topology==="comparative_proof"||topology==="three_peer_comparison"){
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:C.text,bold:true,name:"primary-headline"});
    if(content.data?.length)addNativeChart(slide,content,evidenceBox,false);else addMetricSystem(slide,content.metrics?.length?content.metrics:content.items?.map((x,i)=>({value:String(i+1).padStart(2,"0"),label:itemValue(x)})),evidenceBox,{dark:false,max:topology==="three_peer_comparison"?3:5});
  }else if(topology==="three_stage_progression"||topology==="ordered_domains"||topology==="methodology_scope"){
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:C.text,bold:true,name:"primary-headline"});const items=(content.columns||content.items||content.bullets||content.body||[]).slice(0,topology==="three_stage_progression"?3:6),count=Math.max(items.length,1),gap=20,width=(evidenceBox.width-gap*(count-1))/count;items.forEach((item,index)=>{const field={left:evidenceBox.left+index*(width+gap),top:evidenceBox.top,width,height:evidenceBox.height};addBroadField(slide,field,{name:`semantic-field-${index+1}`});addGradientMark(slide,{left:field.left,top:field.top,width:field.width,height:10},palette);text(slide,typeof item==="object"?item.title||item.label||`0${index+1}`:`0${index+1}`,{left:field.left+20,top:field.top+30,width:field.width-40,height:55},{fontSize:22,color:C.text,bold:true,name:`field-title-${index+1}`});text(slide,typeof item==="object"?(item.items||[]).join("\n\n")||item.body||itemValue(item):itemValue(item),{left:field.left+20,top:field.top+104,width:field.width-40,height:field.height-135},{fontSize:15,color:C.text,name:`field-body-${index+1}`});});
  }else if(topology==="objective_action_result_quote"){
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:C.text,bold:true,name:"primary-headline"});const gap=24,width=(evidenceBox.width-gap)/2,left={left:evidenceBox.left,top:evidenceBox.top,width,height:evidenceBox.height},right={left:evidenceBox.left+width+gap,top:evidenceBox.top,width,height:evidenceBox.height};addBroadField(slide,left,{name:"objective-action-field"});addBroadField(slide,right,{name:"result-field"});text(slide,"Objective",{left:left.left+26,top:left.top+24,width:left.width-52,height:30},{fontSize:16,bold:true,name:"objective-label"});text(slide,content.objective||"",{left:left.left+26,top:left.top+66,width:left.width-52,height:82},{fontSize:15,name:"objective"});text(slide,"Action",{left:left.left+26,top:left.top+166,width:left.width-52,height:30},{fontSize:16,bold:true,name:"action-label"});text(slide,content.action||"",{left:left.left+26,top:left.top+205,width:left.width-52,height:95},{fontSize:15,name:"action"});text(slide,"Results",{left:right.left+26,top:right.top+24,width:right.width-52,height:30},{fontSize:16,bold:true,name:"result-label"});text(slide,(content.outcomes||[]).join("\n\n")||(content.metrics||[]).map(x=>`${x.value} ${x.label||""}`).join("\n\n"),{left:right.left+26,top:right.top+75,width:right.width-52,height:210},{fontSize:18,bold:true,name:"results"});if(content.quote)text(slide,content.quote,secondaryBox,{fontSize:20,color:C.text,name:"authority-quote"});
  }else if(topology==="action_protocol"){
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:C.text,bold:true,name:"primary-headline"});const items=(content.items||content.bullets||[]).slice(0,8),splitAt=Math.ceil(items.length/2),groups=[items.slice(0,splitAt),items.slice(splitAt)],gap=28,width=(evidenceBox.width-gap)/2;groups.forEach((group,index)=>{const field={left:evidenceBox.left+index*(width+gap),top:evidenceBox.top,width,height:evidenceBox.height};addBroadField(slide,field,{name:`action-field-${index+1}`});group.forEach((item,row)=>{shape(slide,"ellipse",{left:field.left+25,top:field.top+28+row*76,width:28,height:28},C.blue,"none",`check-${index}-${row}`);text(slide,"✓",{left:field.left+31,top:field.top+31+row*76,width:16,height:16},{fontSize:12,color:C.white,bold:true,alignment:"center",name:`checkmark-${index}-${row}`});text(slide,itemValue(item),{left:field.left+70,top:field.top+24+row*76,width:field.width-98,height:58},{fontSize:14,color:C.text,name:`action-${index}-${row}`});});});
  }else if(topology==="risk_evidence_quote"){
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:C.text,bold:true,name:"primary-headline"});text(slide,bodyValue(content),{left:clusterBox.left,top:headlineBox.top+headlineBox.height+20,width:Math.max(400,evidenceBox.left-clusterBox.left-40),height:240},{fontSize:16,name:"risk-narrative"});addBroadField(slide,secondaryBox,{name:"warning-field"});text(slide,content.warning||(content.metrics||[])[0]?.value||"",{left:secondaryBox.left+24,top:secondaryBox.top+25,width:secondaryBox.width-48,height:70},{fontSize:36,bold:true,name:"warning-metric"});text(slide,content.quote||content.quotes?.[0]?.text||"",evidenceBox,{fontSize:26,name:"authority-quote"});
  }else{
    text(slide,content.title||record.coreClaim,headlineBox,{fontSize:titleSize,color:C.text,bold:true,name:"primary-headline"});const body=bodyValue(content)||(content.bullets||[]).join("\n\n");text(slide,body,{left:clusterBox.left,top:headlineBox.top+headlineBox.height+24,width:Math.min(720,clusterBox.width*.64),height:Math.max(180,clusterBox.height-headlineBox.height-30)},{fontSize:18,color:C.text,name:"narrative-body"});await addSourceImage(slide,content,evidenceBox);
  }
  addSource(slide,content,dark||record.templateId==="T07");addFooter(slide,record.outputSlide,dark||record.templateId==="T07");
}

for(const record of plan.slides)await renderSlide(record);
const pptx=await PresentationFile.exportPptx(deck);await pptx.save(output);
await writeJson(path.join(work,"renderer-v5-report.json"),{plannerVersion:plan.plannerVersion,output,slideCount:plan.slides.length,compositionConsumed:plan.slides.every(x=>x.composition_solution?.solver_status==="feasible"),templateMatchesConsumed:plan.slides.every(x=>x.template_match?.selected_primitive===x.templateId),assetSelectionsConsumed:plan.slides.filter(x=>x.asset_selection?.status==="matched").map(x=>({slide:x.outputSlide,asset_id:x.asset_selection.asset_id,position:x.composition_solution.asset_visible_region})),editableObjectPolicy:{text:true,charts:true,diagrams:true,icons:true,layoutObjects:true,wholeSlideRasterization:false}});
console.log(`output=${output} slides=${plan.slides.length} renderer=5.0 assets=${plan.slides.filter(x=>x.asset_selection?.status==="matched").length}`);
