import path from "node:path";import {args,need,readJson,writeJson,numericTokens} from "./lib/common.mjs";
const a=args(),work=path.resolve(need(a,"work")),inv=await readJson(path.join(work,"content-inventory.json")),plan=await readJson(path.join(work,"deck-plan.json"));
const scrub=v=>Array.isArray(v)?v.map(scrub):v&&typeof v==="object"?Object.fromEntries(Object.entries(v).filter(([k])=>!["images","imageLayout","assets","imageIntent","relationshipId","entry","mediaEntry","fileName","recoverability","id","path","needsReview"].includes(k)).map(([k,x])=>[k,scrub(x)])):v;const visible=c=>JSON.stringify(scrub(c||{}));
const inputText=inv.slides.map(s=>[s.title,...s.bodyBlocks,...s.bullets,...s.sources,...s.quotes.map(q=>`${q.text||""} ${q.attribution||""}`),...s.charts.flatMap(c=>(c.series||[]).flatMap(v=>[v.name,...(v.categories||[]),...(v.values||[])])),...s.tables.flatMap(t=>(t.rows||[]).flat())].join(" ")).join(" ");
const outputText=plan.slides.map(s=>visible(s.content)).join(" "),input=numericTokens(inputText),output=numericTokens(outputText),inputSet=new Set(input),outputSet=new Set(output),isIndex=x=>/^\d+$/.test(x)&&Number(x)>=1&&Number(x)<=inv.slideCount;
const missing=[...inputSet].filter(x=>!outputSet.has(x)&&!isIndex(x)),added=[...outputSet].filter(x=>!inputSet.has(x)&&!isIndex(x)),issues=[...missing.map(value=>({severity:"critical",code:"NUMBER_OR_UNIT_MISSING",value})),...added.map(value=>({severity:"critical",code:"NUMBER_OR_UNIT_UNTRACED",value}))];
for(const slide of inv.slides){for(const source of slide.sources||[])if(source&&!outputText.includes(source))issues.push({severity:"critical",code:"SOURCE_MISSING",sourceSlide:slide.sourceSlide,source});for(const quote of slide.quotes||[]){if(quote.text&&!outputText.includes(quote.text))issues.push({severity:"critical",code:"QUOTE_MISSING",sourceSlide:slide.sourceSlide,text:quote.text});if(quote.attribution&&!outputText.includes(quote.attribution))issues.push({severity:"critical",code:"QUOTE_ATTRIBUTION_MISSING",sourceSlide:slide.sourceSlide,attribution:quote.attribution});}}
for(const slide of plan.slides){if(!Array.isArray(slide.sourceSlides)||!slide.sourceSlides.length)issues.push({severity:"critical",code:"SOURCE_SLIDE_MAPPING_MISSING",outputSlide:slide.outputSlide});if((slide.retainedEvidence||[]).some(e=>typeof e==="object"&&e.needsReview))issues.push({severity:"major",code:"RETAINED_EVIDENCE_NEEDS_REVIEW",outputSlide:slide.outputSlide});}
const report={category:"content",status:issues.some(x=>x.severity==="critical")?"fail":issues.length?"warning":"pass",issues,counts:{inputNumbers:input.length,outputNumbers:output.length,inputUnique:inputSet.size,outputUnique:outputSet.size,sourceSlides:inv.slideCount,outputSlides:plan.slides.length},note:"Sequential integers within the source slide count are treated as structural indices. Images and image-intent metadata are excluded from factual token checks."};await writeJson(path.join(work,"qa-content.json"),report);console.log(JSON.stringify(report.counts));if(report.status==="fail")process.exitCode=2;
